name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/poetry-plugin-lambda-build-v2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install poetry
        shell: bash
        run: pipx install poetry

      - name: Build package
        run: poetry build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
